[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-dev-dep-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
parcel-resolver = { path = "../node-resolver-rs" }
es-module-lexer = { path = "/Users/devongovett/dev/es-module-lexer" }
serde_json = "*"
rayon = "*"
dashmap = "*"
memmap = "*"
glob = "*"
